const MEMBERS = [
  { nama: "Renji Ishida", code: "X5M0329E", pangkat: "Warlord", spesialisasi: "Engineer" },
  { nama: "Den Bagaskara", code: "I532T0UY", pangkat: "Right Hand", spesialisasi: "Medic" },
  { nama: "Jackie Chen", code: "O91JZR97", pangkat: "Right Hand", spesialisasi: "Medic" },
  { nama: "Jester Mourance", code: "M8Y8620P", pangkat: "Right Hand", spesialisasi: "Scavenger" },
  { nama: "Ragna Rowr", code: "Z30199WY", pangkat: "Right Hand", spesialisasi: "Engineer" },
  { nama: "Zami Mourance", code: "A99VVM4Z", pangkat: "Right Hand", spesialisasi: "Engineer" },
  { nama: "Ali Xander", code: "NYE41BTD", pangkat: "Enforcer", spesialisasi: "Survivalist" },
  { nama: "Anna Topuk", code: "MDUCME8S", pangkat: "Enforcer", spesialisasi: "Medic" },
  { nama: "Antin Surintin", code: "P9AG4307", pangkat: "Enforcer", spesialisasi: "Survivalist" },
  { nama: "Arinara Mourgrace", code: "E8E659MX", pangkat: "Enforcer", spesialisasi: "Medic" },
  { nama: "Bolu Elchoppa", code: "DQM76L59", pangkat: "Enforcer", spesialisasi: "Medic" },
  { nama: "Ciro G Druzillach", code: "S1EK94XA", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Clyde V Larvertse", code: "F2H067D2", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Gabe Nelson", code: "J1QL62FA", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Gohan Han", code: "E870V8R3", pangkat: "Enforcer", spesialisasi: "Medic" },
  { nama: "Gray Ravenwolf", code: "M52RJEPO", pangkat: "Enforcer", spesialisasi: "Engineer" },
  { nama: "Hen Saviero", code: "E64XMC3V", pangkat: "Enforcer", spesialisasi: "Survivalist" },
  { nama: "Ibim Sugeni", code: "ZAVBYR82", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Intin Sirintin", code: "GF3JLYBJ", pangkat: "Enforcer", spesialisasi: "Engineer" },
  { nama: "Jax Mercer", code: "DR3WRJ5O", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Katya Claire", code: "QD2S55L0", pangkat: "Enforcer", spesialisasi: "Medic" },
  { nama: "Leo Rampage", code: "IGWT961V", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Levi Lee", code: "C038I66N", pangkat: "Enforcer", spesialisasi: "Engineer" },
  { nama: "Makh Rony", code: "LX2BBY3K", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Rd Kydon", code: "W2D26KOH", pangkat: "Enforcer", spesialisasi: "Survivalist" },
  { nama: "Rogeer Pradipta", code: "M5P5HND5", pangkat: "Enforcer", spesialisasi: "Engineer" },
  { nama: "Star Claire", code: "B050I06J", pangkat: "Enforcer", spesialisasi: "Scavenger" },
  { nama: "Viieeyy R", code: "I60OFYEK", pangkat: "Enforcer", spesialisasi: "Survivalist" },
  { nama: "Wayan Redvelvet", code: "EL85735S", pangkat: "Enforcer", spesialisasi: "Survivalist" },
  { nama: "Agie Pratama", code: "CK40H1HB", pangkat: "Youngblood", spesialisasi: "Scavenger" },
  { nama: "Aldeen Sss", code: "I38A5661", pangkat: "Youngblood", spesialisasi: "Engineer" },
  { nama: "Bimbim Mosyi", code: "C69U9YP6", pangkat: "Youngblood", spesialisasi: "Medic" },
  { nama: "Kenizio Alucard", code: "V3W8AT61", pangkat: "Youngblood", spesialisasi: "Scavenger" },
  { nama: "Kurjawa Sankor", code: "T53E6XW4", pangkat: "Youngblood", spesialisasi: "Engineer" },
  { nama: "Lyra Nyx", code: "VB78IZXT", pangkat: "Youngblood", spesialisasi: "Medic" },
  { nama: "Miche De Liche", code: "X8R454AM", pangkat: "Youngblood", spesialisasi: "Survivalist" },
  { nama: "Morven Zade", code: "D5Z61D33", pangkat: "Youngblood", spesialisasi: "Scavenger" },
  { nama: "Nevan K Montana", code: "C5Y1JY3R", pangkat: "Youngblood", spesialisasi: "Engineer" },
  { nama: "Ray Kyodo", code: "F99CA2N6", pangkat: "Youngblood", spesialisasi: "Scavenger" },
  { nama: "Samuel Kevyn", code: "RM641TKG", pangkat: "Youngblood", spesialisasi: "Medic" },
  { nama: "Sugeng Makaryo", code: "GZAL1627", pangkat: "Youngblood", spesialisasi: "Medic" },
  { nama: "Tobi Kedip", code: "NH03B8I1", pangkat: "Youngblood", spesialisasi: "Scavenger" },
  { nama: "Viggo Ashley", code: "E4010QZ9", pangkat: "Youngblood", spesialisasi: "Medic" },
  { nama: "Zack Melonn", code: "P5CSS206", pangkat: "Youngblood", spesialisasi: "Survivalist" }
];
